application: sharetaxi6
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /syncMemNdb
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on
